In [1]:
import pandas as pd

In [2]:
df_dirty = pd.read_csv('../data/titanic.csv')

df_dirty.head(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C

In [3]:
df_cl = pd.read_csv('../data/titanic_clean.csv')

df_cl.head(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,Desconhecido,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,Desconhecido,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,Desconhecido,S
5,6,0,3,"Moran, Mr. James",male,28,0,0,330877,8.4583,Desconhecido,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.0750,Desconhecido,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,Desconhecido,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,Desconhecido,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20,0,0,A/5. 2151,8.0500,Desconhecido,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39,1,5,347082,31.2750,Desconhecido,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14,0,0,350406,7.8542,Desconhecido,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55,0,0,248706,16.0000,Desconhecido,S
16,17,0,3,"Rice, Master. Eugene",male,2,4,1,382652,29.1250,Desconhecido,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,28,0,0,244373,13.0000,Desconhecido,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31,1,0,345763,18.0000,Desconhecido,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,28,0,0,2649,7.2250,Desconhecido,C

In [4]:
df_tratado = pd.read_csv('../data/titanic_tratado.csv')

df_tratado.head(20)

,PassengerId,Survived,Pclass,Name,Age,NrFamiliares,Ticket,Fare,Cabin
0,b2c01aa6,0,ae6a,6c969dc7ad8ff99ae4959829c664e8537f5f98a23f41c1...,Adulto,Pequena,A/5****,menos que $100,Desconhecido
1,40d6a98a,1,8228,f7ad2d69edefb38cae0679b6e6a8953b3f5892c9d12a57...,Adulto,Pequena,PC ****,menos que $100,C
2,34658ad9,1,ae6a,7eb1fa77712a2b7aae183c39084f0ea0c9399488229bc2...,Adulto,Sem familiares,STO****,menos que $100,Desconhecido
3,c341f6a5,1,8228,c8a06e7446f04298d047e50e9ae4df4b0b63a437da6762...,Adulto,Pequena,113****,menos que $100,C
4,fe4733a9,0,ae6a,885e53ea6ed5a0ed33e075f1ebe2453a6c9eb1aa84053d...,Adulto,Sem familiares,373****,menos que $100,Desconhecido
5,a91b656c,0,ae6a,fab68f7e6f04b8fb5b7abc3a2e99873834491acd1d34ee...,Adulto,Sem familiares,330****,menos que $100,Desconhecido
6,3cd8d40e,0,8228,558f7a8586015ef0608611c686374b01155a139c263a72...,Adulto,Sem familiares,174****,menos que $100,E
7,59227a7f,0,ae6a,cbd46ee4bc70d2641f1d1d5679915d6bebe00471ed6f7a...,Menor,Grande,349****,menos que $100,Desconhecido
8,b3ebeee0,1,ae6a,3f3b1d436a7574b993ffe759313b5fbfa41941c072d82c...,Adulto,Pequena,347****,menos que $100,Desconhecido
9,7e85c3d3,1,300d,c54fde5d501e974201ef04f4890fb11e42b64c1d5a6149...,Menor,Pequena,237****,menos que $100,Desconhecido
10,b8c7922a,1,ae6a,97901174ab27c6de5e7bdd424a2ee9e0f77ce38227ee0d...,Menor,Pequena,PP ****,menos que $100,G
11,1631c9c8,1,8228,0eb86cd7de54024678fe30b3a78ddf41d8918cff12a680...,Adulto,Sem familiares,113****,menos que $100,C
12,412e1779,0,ae6a,0384acda8f41266d3e8a91e9e01e33d071957b78f0b5b1...,Adulto,Sem familiares,A/5****,menos que $100,Desconhecido
13,9927dd52,0,ae6a,a985d9cfe2eaf27b2723e9f024d2438744fc001afb7f0d...,Adulto,Grande,347****,menos que $100,Desconhecido
14,49e21327,0,ae6a,d8e1ad4da6633c639de91f9cc70df8a8839be95abda727...,Menor,Sem familiares,350****,menos que $100,Desconhecido
15,f4edbe98,1,300d,e46eaa968c1b2f9904eb9bfd6e31d7ce06af777ac7b6de...,Adulto,Sem familiares,248****,menos que $100,Desconhecido
16,02828e72,0,ae6a,f508fe559752338d5175219848de667feece60fe0917e5...,Menor,Grande,382****,menos que $100,Desconhecido
17,9a2b0136,1,300d,511a68b4797b43fe119b32964a841969a29812153a7ef2...,Adulto,Sem familiares,244****,menos que $100,Desconhecido
18,51f33e4f,0,ae6a,236eeffbf3b6066444d23529dd3b2392cbb24756ce537d...,Adulto,Pequena,345****,menos que $100,Desconhecido
19,bb9e4779,1,ae6a,85e474371158d92cf90323d3e57e007640c5c6953fa10d...,Adulto,Sem familiares,264****,menos que $100,Desconhecido